[tool.cmake]
experimental = true
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.packages = []
cmake.build-type = "Release"
#wheel.install-dir = "leptoninjector"

[tool.scikit-build.cmake.define]
BLAH = "ON"

[tool.cibuildwheel]
before-all = "yum install -y cfitsio-devel; pip install scikit-build-core"

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair --exclude photospline -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[project]
name = "leptoninjector"
version = "0.0.1"
requires-python = ">=3.7"

[wheel]
no-clean = true

[install]
no-clean = true
